### ISSUE TITLE
How to use command to reload config?

### ISSUE THREAD

**Issue by huntersxy** [ezTxmMC/LuckPrefix#6]

**Comment by ezTxmMC** [comment]
It should be the '/luckprefix reloadconfigs' command. Try it, come back and tell me the result.

**Comment by huntersxy** [comment]
![image](https://github.com/user-attachments/assets/dfca06df-d8a5-4b2a-b9f4-70d51c4eb100)
it can't be used

**Comment by huntersxy** [comment]
i am op,so i think i have all Permissions

**Comment by ezTxmMC** [comment]
i will check this after my 1 week vacation.

**Comment by ezTxmMC** [comment]
Sorry for the long waiting. I had checked it and in the newest version of luckprefix the command to reload the configs is "/luckprefix reloadconfig".
