### ISSUE TITLE
No automatic update of tab and chat prefix when changing parent element.

### ISSUE THREAD

**Issue by mettemfurfur000** [ezTxmMC/LuckPrefix#7]
hiiiii 

i think u forgor to listen to https://github.com/LuckPerms/LuckPerms/blob/master/api/src/main/java/net/luckperms/api/event/user/UserDataRecalculateEvent.java but i don write java as much

**Comment by ezTxmMC** [comment]
> hiiiii
> 
> i think u forgor to listen to https://github.com/LuckPerms/LuckPerms/blob/master/api/src/main/java/net/luckperms/api/event/user/UserDataRecalculateEvent.java but i don write java as much

This problem is already known, but I forget to fix it.
I will try to fix it still this year in update 2.0.0-BETA+7.

Thank you also for reporting the problem and your help in improving my plugin.
